version: '3.8'

services:
  postgres:
    image: ankane/pgvector:v0.5.1
    container_name: mcp-postgres-dev
    environment:
      - POSTGRES_DB=mcp_docs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Development Qdrant instance
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mcp-qdrant-dev
    ports:
      - "6333:6333"
    volumes:
      - qdrant_dev_data:/qdrant/storage
    restart: unless-stopped

  # Ollama for local embeddings during development
  ollama:
    image: ollama/ollama:latest
    container_name: mcp-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_dev_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_dev_data:
  qdrant_dev_data:
  ollama_dev_data: